name: lint

on:
  pull_request:
    branches:
      - development
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup-backend-node-modules:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: ./node_modules
        key: backend-node_modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node_modules-

    - name: Install dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: npm ci

  lint:
    needs: [setup-backend-node-modules]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Load backend dependencies
      uses: actions/cache@v2
      with:
        path: ./backend/node_modules
        key: backend-node_modules-${{ hashFiles('package-lock.json') }}

    - name: Lint
      run: npm run lint